### PR TITLE
Fix filesystem error. 

### PR DESCRIPTION
**Pull request by roangel**
Doc: https://forums.developer.nvidia.com/t/nvidia-sdk-manager-on-docker-container/76156/18

After this, I don't get the problems of the type:
`ERROR : File System and OS : chroot: failed to run command 'dpkg': Exec format error.`

### CODE REVIEW

**Comment by atinfinity** [comment]
@roangel Thank you for your contribution! But, I could not reproduce this problem.
So, could you give me the following information?

- OS version of host PC
- Docker version
- SDK Manager version
- Procedure to reproduce this problem

**Comment by roangel** [comment]
> @roangel Thank you for your contribution! But, I could not reproduce this problem.
> So, could you give me the following information?
> 
> * OS version of host PC
> * Docker version
> * SDK Manager version
> * Procedure to reproduce this problem

Hi @atinfinity , yes sure:
   - Ubuntu 20.04 host PC
   - Docker version 19.03.8, build afacb8b7f0
   - sdkmanager_1.3.1-7110_amd64
   - Reproduce steps:
            1. Run the docker container
            2. start sdkmanager, login with your Nvidia developer account
            3. Select Jetson as product category, disable host machine, select jetson tx2 hardware, select jetpack 4.4 as target operating system, do not include additional sdks. Go to next step
            4. Accept license and continue to next step
            5. Wait until it downloads everything and when it's building the OS image, at around 10% of the general process, the error prompts and the process fails.

**Comment by atinfinity** [comment]
@roangel Thank you for your additional information. I'll try to reproduce.

**Comment by atinfinity** [comment]
LGTM!

**Comment by MiroPsota** [comment]
This is not correct, only the last CMD will be executed.
Furthermore, in `launch_container.sh` `bash` command is explicitly declared so `CMD` will not be executed.
One possible solution is in https://github.com/MiroPsota/sdkmanagerGUI_docker, where is created files with command.

**Pull request merged**
