### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by satyajitghana**
Add the QEMU error in README.md

### CODE REVIEW

**Comment by atinfinity** [comment]
@satyajitghana Thank you for your contribution! Now, the `configure_qemu.sh` is executed with `docker run`. Did described error occur?
https://github.com/atinfinity/sdk_manager_docker/blob/62428020d8b3a0b6cf065fef2fc59d68d212660d/Dockerfile#L68

**Comment by satyajitghana** [comment]
Yes, for some reason it still did, I had to rerun the commands again on a running container to get it to work. I'm not sure why though.

**Comment by MiroPsota** [comment]
`CMD` is executed when no command is specified in `docker run`. In this repo container is launched as `docker run <args> bash`, so `bash` overrides `CMD <command>`.
To solve this, you need to launch container with something like `docker run <args> bash -c "sudo /home/${USERNAME}/configure_qemu.sh; bash"`.

**Comment by atinfinity** [comment]
@satyajitghana @MiroPsota  Thank you for your comment. I'll consider measures to resolve this problem. So, please wait a little.

**Comment by atinfinity** [comment]
LGTM!

**Comment by satyajitghana** [comment]
👍

**Pull request merged**
